### ISSUE TITLE
Idea: generate README.md from README.qmd for reproducibility

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/routing-engines#1]
The 

    ```bash

code in there can run with `quarto render README.qmd` improving reproducibility.

Could set

```bash
#| eval: false
```

for the computationally intensive chunks or could just run the whole thing on any suitably resourced computer.

I plan to give this a bash over the next couple of weeks in any case, impressive speed-ups compared with routing used by PCT from what I can tell.

**Comment by dabreegster** [comment]
Thanks for the idea, but I'm pretty against the use of quarto or similar here. The output from most of these commands is just noise. And unless the output README.md document is completely deterministic and quickly generated on every commit by GH actions, then it's just something that'll get out of sync. Most of the shell commands are temporary, getting bundled up into a CLI or web UI.

The readme right now is broken/meaningless; I'll rewrite it when things are ready for a wider look

**Comment by Robinlovelace** [comment]
Sounds fine to me. Generating on every commit is something that can happen for sure with one of these: https://github.com/quarto-dev/quarto-actions

Closing for now but I think something that ensured up-to-date-ness in the readme would be good, and README.qmd is just one option of many...
