### ISSUE TITLE
SoTM submission?

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/routing-engines#4]
Deadline: 24th August. 

https://twitter.com/osmscience/status/1688249220954812417

**Comment by dabreegster** [comment]
You read my mind ;)  I'm leaning heavily towards a [60 minute workshop](https://stateofthemap.eu/call-for-participation), possibly around an "end-to-end active travel planning" flow. Lead people through building a simple demand model using this repo, then sketching possible interventions using ATIP, and possibly dropping down to designing in detail using the LTN tool or A/B Street. Thoughts?

**Comment by Robinlovelace** [comment]
Sounds good and happy to collaborate on this!
