### ISSUE TITLE
Observations on reproducing outputs

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/routing-engines#5]
Just a heads-up after reproducing some of the code in the README, managed to get this map which I'm happy with :tada: 

![image](https://github.com/dabreegster/routing-engines/assets/1825120/8f28061f-f8a7-4632-8076-b9d307ca0d6f)

FYI anyone running this on Ubuntu, you may need to update your node version. This is what worked for me after reading [this](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04).

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.bashrc
nvm list-remote
nvm install v18.12.0
nvm use v18.12.0
```

**Comment by Robinlovelace** [comment]
Headline: you need a reasonably up-to-date version of `nodejs`. Worth adding that to the README?

**Comment by dabreegster** [comment]
Note the origin/destination layers shown are currently hardcoded paths to Cornwall. Change the symlinks in `viewer/assets` if needed. This is temporary.

**Comment by Robinlovelace** [comment]
Follow-up, got the routes displayed now also!

![image](https://github.com/dabreegster/routing-engines/assets/1825120/c689a19b-148b-4ecb-a503-17f8265f35d7)
