### ISSUE TITLE
Example instructions for Leeds hospital

### ISSUE THREAD

**Issue by dabreegster** [dabreegster/routing-engines#6]
From every building to https://www.openstreetmap.org/way/23196317:

```shell
AREA=leeds
URL=https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf

mkdir $AREA
curl $URL -o $AREA/input.osm.pbf
ogr2ogr -f GeoJSON -dialect sqlite -sql 'SELECT ST_Centroid(geometry) FROM multipolygons WHERE building IS NOT NULL' $AREA/origins.geojson $AREA/input.osm.pbf
# For destinations, just one hospital: https://www.openstreetmap.org/way/23196317
echo '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[-1.5521021406315,53.80241788159283],"type":"Point"}}]}' > $AREA/destinations.geojson

# Generate the "fast" network
cargo run --release -- '{"directory":"'"$AREA"'","requests":{"Generate":{"pattern":"FromEveryOriginToOneDestination"}},"routing":{"FastPaths":{"cost":"Distance"}}}'
mv $AREA/output.geojson $AREA/fast_output.geojson

# Now a rough approximation of a "quiet" network, penalizing main roads heavily
rm -f $AREA/ch.bin
cargo run --release -- '{"directory":"'"$AREA"'","requests":{"Generate":{"pattern":"FromEveryOriginToOneDestination"}},"routing":{"FastPaths":{"cost":"AvoidMainRoads"}}}'
mv $AREA/output.geojson $AREA/quiet_output.geojson
```

Manually load the two leeds/{fast,quiet}_output.geojson files in the viewer

**Comment by dabreegster** [comment]
Downloading + generating everything above took about 2 minutes for me. Ignore the origin/destination layer in the viewer, since it's still hardcoded to Cornwall.

The fast network:
![Screenshot from 2023-08-07 14-00-40](https://github.com/dabreegster/routing-engines/assets/1664407/5833805b-1ea8-4e74-8742-907b99103707)

The quiet:
![Screenshot from 2023-08-07 14-00-49](https://github.com/dabreegster/routing-engines/assets/1664407/7a259235-df0f-4b04-b7c5-9a6a6a6c21ac)
Note the canal towpath really lights up.

Don't forget all the caveats about this **early** demo. Starting from every single building and going to one hospital is a really unrealistic pattern. And some of these resulting routes are much longer than people would realistically use.

**Comment by Robinlovelace** [comment]
Progress here... 
![image](https://github.com/dabreegster/routing-engines/assets/1825120/ba19e42e-8694-48d2-960b-f9ccae055ccf)

**Comment by Robinlovelace** [comment]
Works great, thanks Dustin! 

![image](https://github.com/dabreegster/routing-engines/assets/1825120/43423e26-ea72-4a36-b9d9-8af9e5d64b7a)

**Comment by Robinlovelace** [comment]
Complete for sure. I plan to open an issue at some point re Alder Hay hospital in Liverpool.
